services:
  quiz-db:
    image: postgres:latest
    ports:
      - "${DB_DEV_PORTS}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - quiz_network

networks:
  quiz_network:
